config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  get 'fabs/create'
  get 'fabs/destroy'
  devise_for :users, 
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
  registrations: 'users/registrations',
  sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"    
    get "logout", :to => "users/sessions#destroy"
    root :to => "users/sessions#new"  
  end

  # root to: "posts#index"
  # get "login", :to => "users/sessions#new"
  
  # get '/users/:id', to: 'users#show', as: 'user'
  # get '/users', to: 'users#index'
#　↑resourcesと被らないか。
  
  # resources :users do
  #   resource :relationships, only: [:create, :destroy]
  #   get :follows, on: :member # 追加
  #   get :followers, on: :member # 追加
  # end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,only: [:create, :destroy] 
  
  resources :posts, only: %i(new create show destroy index) do
    resources :comments, only: %i(create destroy)
    resources :fabs, only: %i(create destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  # deviseの後ろに書いてあるのはモジュール
  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: true  
  # facebook実装用
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        image:  auth.info.image
      )
    end
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy  
  has_many :fabs, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  
    # allow users to update their accounts without passwords
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  protected
 
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  
  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end

  def index
    @users=User.all
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def logged_in?
      !current_user.nil?
    end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= button_tag "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_modify.html.erb
<!--入力他、あとで削除する？-->
<% if @user == current_user %>
  <div class="row">
    <div class="col-md-4"><%= image_tag "facebook_icon.png", :size =>'50x50' %>
      <h4>facebookの友達を検索</h4>
      <p>フォローする人は自分で選択できます。また、アカウントをリンクしても、あなたの許可なくFacebookに投稿されることはありません。</p>
      <%= link_to "facebookアカウントにリンク", "#", class: "btn btn-primary" %>
    </div>
    <div class="col-md-4"><%= image_tag "tel_icon.png", :size =>'50x50' %>
      <h4>電話番号を追加</h4>
      <p>電話番号を追加すると、パスワードのリセットや友達の検索などに使用することができます。</p>
      <%= link_to "電話番号を追加", "#", class: "btn btn-primary" %>
    </div>
    <div class="col-md-4"><%= image_tag "camera_icon.png", :size =>'50x50' %>
      <h4>プロフィール写真を追加</h4>
      <p>友達に簡単に見つけてもらえるよう、プロフィール写真を追加してください。</p>
      <%= link_to "プロフィール写真を追加", "#", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    フォロー中
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    人
  </a>
  <a href="<%= followers_user_path(@user) %>">
    フォロワー
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    人
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= button_tag "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <hr>
  <div class="row d-sm-flex justify-content-between">
    <div class="col-sm-2">
      <%= image_tag avatar_url(user), class: "rounded-circle", :size =>'40x40' %>
    </div>
    <div class="col-sm-6">
      <p><span>username: </span><%=link_to user.name, user_path(user.id) %></p>
    </div>
    <!--フォロー-->
    <div class="col-sm-4">
      <% unless current_user == user %>
        <div id="follow_form", class="d-flex">
        <% if current_user.following?(@user,user) %>
          <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "m-round-img" %>
      <!--フォロー-->
      <%= render 'follow_form' if user_signed_in? %>
    </div>
    <div class="col-md-8">
      <!--プロフィール画面-->
      <div class="row">
        <h1><%= @user.name %></h1>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn m-edit-profile-btn" %>
          <button type="button" class="m-setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>
      </div>
      <div class="row">
        <% if @user.posts.any? %>
          <p>投稿数　<%= @user.posts.count %>　　</p>
        <% end %>
        <section class="d-block">
          <%= render 'stats' %>
        </section>
        <% if @user == current_user %>
          <div class="text-center">
            <%= link_to "投稿", new_post_path, class: "btn btn-outline-dark common-btn" %>
          </div>
        <% end %>
      </div>
      <hr>
    </div>
    <!--投稿内容-->
    <div class="row d-sm-flex justify-content-between flex-wrap">
      <% @posts.each do |post| %>
        <div class="col-sm-4">
          <p><%= link_to image_tag(post.contain.url(:gallery)), post_path(post) %></p>
        </div>
      <% end %>
    </div>
    <hr>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <%= image_tag avatar_url(@user), class: "rounded-circle", :size =>'60x60' %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
      <span><b>投稿</b> <%= @user.posts.count %></span>
    </section>
  </aside>
  <div class="col-md-6">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %> 
          <hr>
          <div class="d-flex">
            <%= image_tag avatar_url(user), class: "rounded-circle", :size =>'40x40' %>
            <h4><%= link_to user.name, user_path(user) %></h4>
          <div>
        <% end %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>