config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  get 'fabs/create'
  get 'fabs/destroy'
  devise_for :users, 
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
  registrations: 'users/registrations',
  sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"    
    get "logout", :to => "users/sessions#destroy"
    root :to => "users/sessions#new"  
  end

  # root to: "posts#index"
  # get "login", :to => "users/sessions#new"
  
  # get '/users/:id', to: 'users#show', as: 'user'
  # get '/users', to: 'users#index'
#　↑resourcesと被らないか。
  
  # resources :users do
  #   resource :relationships, only: [:create, :destroy]
  #   get :follows, on: :member # 追加
  #   get :followers, on: :member # 追加
  # end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,only: [:create, :destroy] 
  
  resources :posts, only: %i(new create show destroy index) do
    resources :comments, only: %i(create destroy)
    resources :fabs, only: %i(create destroy)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  # default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :contain, presence: true
  
  has_many :comments, dependent: :destroy
  has_many :fabs, dependent: :destroy
   
  def fabd_by(user)
    # user_idとpost_idが一致するfabを検索する
    Fab.find_by(user_id: user.id, post_id: id)
  end
  
  mount_uploader :contain, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]  # deviseのメソッドで「ログインしていないユーザーをログイン画面に送る」メソッド
  before_action :correct_user,   only: :destroy
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.all
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def destroy
    @post.destroy!
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end

  private
    def post_params
      params.require(:post).permit(:contain,:textcomment,:fab)
    end

    def correct_user
      @post = Post.find_by(id: params[:id])
      redirect_to root_url if @post&.user != current_user
    end
end

app/views/posts/_fab_text.html.erb
<strong>
  <% fabs.each.with_index do |fab, index| %>
    <% if fabs.size == 1 %>
      <%= fab.user.name %> </strong> が「いいね！」しました
    <% elsif fab == fabs.last %>
      </strong>and<strong>
      <%= + fab.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (fabs.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == fabs.size-2 || index == 1 %>
      <%= fab.user.name %>
    <% else %>
      <%= fab.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_form.html.erb
<div class="modal-dialog" role="dialog">
  <div class="modal-content">
    <div class="row">
      <div class="col-6">
          <%= image_tag @post.contain.url(:gallery) %>
          <br>
          <%= link_to "←BACK", user_url(@post.id) %>
          <br>
          <% if current_user == @post.user %>
            <%= link_to "投稿を削除する", post_path(@post), method: :delete, data: { confirm: "削除しますか?" } %>
          <% end %>
      </div>
      <div class="col-6">
        <div>
        <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'50x50' %>
        <strong><%= @post.user.name %></strong>
        </div>
        <hr>
        <div id="comments">
          <!--コメント出力-->
          <% @comments.each do |c| %>
            <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'25x25' %>
            <a href="/users/<%= @post.user.id %>"><%= c.user.name %></a>
            <%= c.textcomment %>
              <%= link_to "削除", method: :delete, data: { confirm: "削除しますか?" }, class: "float-right" %>
            <hr>
          <% end %>
        </div>
        <div class="form-group">
          <%= image_tag 'fab-heart-blank.png',:height =>'30' %>
          <hr>
          <!--コメント入力-->
          <%= form_for [@post, @comment], remote: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :textcomment, class: "form-control" %>
            <%= f.submit '投稿' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_formshowmodal.html.erb
<div class="modal-dialog" role="dialog">
  <div class="modal-content">
    <div class="row">
      <div class="col-6">
        <%= image_tag @post.contain.url(:gallery) %><br>
        <%= link_to "←BACK", user_url(@post.id) %><br>
        <% if current_user == @post.user %>
          <%= link_to "投稿を削除する", post_path(@post), method: :delete, data: { confirm: "削除しますか?" } %>
        <% end %>
      </div>
      <div class="col-6">
        <div>
          <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'50x50' %>
          <strong><%= @post.user.name %></strong>
        </div>
        <hr>
        <div>
          <div id="comments">
            <!--コメント出力-->
            <% @comments.each do |c| %>
              <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'25x25' %>
              <a href="/users/<%= @post.user.id %>"><%= c.user.name %></a>
              <div>
                <%= c.textcomment %>
              </div>
              <%= link_to "削除", method: :delete, data: { confirm: "削除しますか?" }, class: "float-right" %>
              <hr>
            <% end %>
          </div>
        </div>
        <div class="form-group">
          <%= image_tag 'fab-heart-blank.png',:height =>'30' %>
          <hr>
          <!--コメント入力-->
          <%= form_for [@post, @comment], remote: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :textcomment, class: "form-control" %>
            <%= f.submit '投稿' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_postdelete.html.erb
<% if current_user == @post.user %>
  <%= link_to "投稿を削除する", post_path(@post), method: :delete, data: { confirm: "削除しますか?" } %>
<% end %>

app/views/posts/index.html.erb
<div class="row d-sm-flex justify-content-between flex-wrap">
  <% @posts.each do |post| %>
    <div class="col-sm-4">
      <div class="m-sample">
        <%= image_tag post.contain.url(:gallery) %>
        <!--マスク-->
        <div class="m-mask">
          <div class="m-caption">
            <ul class="d-flex">
              <li>
                <% if post.fabd_by(current_user).present? %>
                  <%= link_to image_tag("whiteheart_icon.png"), post_fab_path(post.id, post.fabd_by(current_user)), method: :DELETE, remote: true %>
                <% else %>
                  <%= link_to image_tag("redheart_icon.png"), post_fabs_path(post), method: :POST, remote: true %>
                <% end %>
              </li>
              <li><p>1,000</p></li>
              <li><%= link_to image_tag("whitecomment_icon.png"), post_path(post) %></li>
              <li><p>100</p></li> 
            </ul>
          </div>
        </div> <!--ここまでマスク-->
      </div>
    </div>
    <div id="post-modal">
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |f| %>
  <%= f.file_field :contain %>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-6">
      <%= image_tag @post.contain.url(:gallery) %>
      <br>
      <%= link_to "←BACK", user_url(@post.id) %>
      <br>
      <%= render 'postdelete' %>
  </div>
  <div class="col-6">
    <div>
      <a href="/users/<%= @post.user.id %>">
        <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'50x50' %>
        <strong><%= @post.user.name %></strong>
      </a>
    </div>
    <hr>
    <div>
      <div id="comments">
        <!--コメント出力-->
        <% @comments.each do |c| %>
          <%= image_tag avatar_url(@post.user), class: "rounded-circle", :size =>'25x25' %>
          <a href="/users/<%= @post.user.id %>"><%= c.user.name %></a>
          <div>
            <%= c.textcomment %>
          </div>
            <%= link_to "削除", post_comment_path(c), method: :delete, data: { confirm: "削除しますか?" }, class: "float-right" %>
          <hr>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <!--イイネ入力-->
      <%= image_tag 'fab-heart-blank.png',:height =>'30' %>
      
      <hr>
      <!--コメント入力-->
      <%= form_for [@post, @comment], remote: true do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.text_field :textcomment, class: "form-control" %>
        <%= f.submit '投稿' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$("#post-modal").html("<%= escape_javascript(render 'form') %>")
$("#post-modal").modal("show")

app/views/posts/showmodal.js.erb
$("#post-modal").html("<%= escape_javascript(render 'form') %>")
$("#post-modal").modal("show")